export const UnitList = {
    battleship: {
        name: '戦艦',
        info: '',
        color: '#664b52',
        fontColor: 'black',
        size: [5, 1],
        id: 'battleship',
        skillName: '榴弾砲',
        skillInfo: '榴弾を発射し、指定したマスとその周囲8マスのユニットを破壊する。',
        skill: ['fire', 1],
        unitInfo: 'どのマスを指定しても榴弾の発射は行われる。そのため既に砲撃した後のマスや、端にあるマスを指定してしまうと、加害できるマスの数が少なくなってしまう。なるべく周辺に手付かずのマスが多い場所を選ぼう。'
    },
    aircraftCarrier: {
        name: '空母',
        info: '',
        color: '#FF5B3B',
        fontColor: 'black',
        size: [2, 4],
        id: 'aircraftCarrier',
        skillName: '対艦ミサイル',
        skillInfo: 'ミサイルを五発装填し、好きなマス五箇所のユニットを破壊する。',
        skill: ['missile', 5],
        unitInfo: 'ミサイルによる攻撃は仮に命中しなかったとしてもターンが切り替わらない。まだ砲撃していないマスの多いエリアにミサイルを撃ち込み、周辺8マスにユニットがいる場合に表示される至近弾の有無による索敵を行おう。'
    },
    cruiser: {
        name: '巡洋艦',
        info: '',
        color: '#62d881',
        fontColor: 'black',
        size: [1, 4],
        id: 'cruiser',
        skillName: '制圧砲撃',
        skillInfo: 'ランダムなマスに十回砲撃を行う。着弾地点のマスのユニットは破壊される。',
        skill: ['suppression', 10],
        unitInfo: 'ランダムに選ばれるマスの中には既に砲撃を行ったマスは含まれない。そのため、まだ砲撃を行っていないマスだけが常に砲撃される。ゲーム開始直後に使用して敵のユニットの位置を炙り出してもいいし、ゲーム終盤にダメ押しとして使ってもいい。'
    },
    gunboat: {
        name: '砲艦',
        info: '',
        color: '#C412DE',
        fontColor: 'black',
        size: [3, 1],
        id: 'gunboat',
        skillName: '集中砲火',
        skillInfo: '集中的に砲撃を行う。指定したマスと、その上下左右のマスのユニットが破壊される。',
        skill: ['fire', 0],
        unitInfo: '指定したマスプラス上下左右で、合計5個のマスに対して加害ができる。砲撃しようとしているマスに本当にユニットがいるかどうか不安になった時に、このスキルで代わりに砲撃しておけばローリスクで加害できる。'
    },
    destroyer: {
        name: '駆逐艦',
        info: '',
        color: '#37FAD7',
        fontColor: 'black',
        size: [1, 3],
        id: 'destroyer',
        skillName: '縦列斉射',
        skillInfo: '主砲の斉射を行う。指定したマスとその上下のマスのユニットが破壊される。',
        skill: ['fire', 2],
        unitInfo: '指定したマスプラス上下の計3マスしか加害できず、正直に言って火力が低いので、いざというときに頼るには心許ない。ゲーム序盤に相手のユニットの位置を炙り出すために使い捨ててしまおう。'
    },
    submarine: {
        name: '潜水艦',
        info: '',
        color: '#4f7187',
        fontColor: 'black',
        size: [1, 2],
        id: 'submarine',
        skillName: 'アクティブソナー',
        skillInfo: '指定したマスに向けてソナーを発射し、周囲八マスのユニットの有無を確認する。使用するとターンが強制的に終了される。',
        skill: ['sonar', [1, 5]],
        unitInfo: '敵ユニットがいたマスはピンクに、いなかったマスは薄灰色になる。そこにユニットがいるかどうかを確認するだけで、破壊したことにはならないので、次のターンにしっかりと砲撃をして破壊しておこう。なおソナーは敵ユニットの有無は確認するが、そのマスの周辺に敵ユニットがいるかどうかは確認しないので、気をつけておこう。'
    },
    torpedo: {
        name: '水雷艇',
        info: '',
        color: 'skyblue',
        fontColor: 'black',
        size: [2, 1],
        id: 'torpedo',
        skillName: '魚雷発射',
        skillInfo: '指定したマスに向けて魚雷を発射。命中すると起爆し周囲八マスのユニットを破壊する。使用するとターンが強制的に終了される。',
        skill: ['torpied', 0],
        unitInfo: '潜水艦のアクティブソナーなどで事前に敵ユニットの位置を把握しておき、確実に命中するようにしておこう。命中しようがしまいがターンの強制終了は発生するので、外してしまうと撃つだけ損になってしまう。'
    },
}
